FROM matomo:fpm-alpine
RUN apk add --no-cache nginx supervisor unzip

RUN curl -o EnvironmentVariables.zip \
    https://plugins.matomo.org/api/2.0/plugins/EnvironmentVariables/download/5.0.1 \
    && unzip EnvironmentVariables.zip \
    && rm EnvironmentVariables.zip \
    && mv EnvironmentVariables /usr/src/matomo/plugins

RUN curl -o BotTracker.zip \
    https://plugins.matomo.org/api/2.0/plugins/BotTracker/download/5.2.11 \
    && unzip BotTracker.zip \
    && rm BotTracker.zip \
    && mv BotTracker /usr/src/matomo/plugins

RUN curl -o TrackingSpamPrevention.zip \
    https://plugins.matomo.org/api/2.0/plugins/TrackingSpamPrevention/download/5.0.2 \
    && unzip TrackingSpamPrevention.zip \
    && rm TrackingSpamPrevention.zip \
    && mv TrackingSpamPrevention /usr/src/matomo/plugins

RUN rm -r /var/www/html && ln -s /usr/src/matomo /var/www/html

COPY ./config/supervisord/supervisord.conf /etc/
COPY ./config/matomo/config.ini.php /usr/src/matomo/config/

USER www-data
RUN chown -R www-data:www-data /usr/src/matomo && \
    chown -R www-data:www-data /run && \
    chown -R www-data:www-data /var/lib/nginx && \
    chown -R www-data:www-data /var/log/nginx

ENTRYPOINT /usr/bin/supervisord -c /etc/supervisord.conf