services:
  traefik:
    image: traefik:3.0
    command: 
      - --providers.docker=true
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
    restart: always
    ports:
      - 80:80
    networks:
      - web
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  mediawiki:
    image: ghcr.io/coasterpedia/coasterpedia-web@${IMAGE}
    restart: always
    networks:
      - web
    volumes:
      - ./config/mediawiki/LocalSettings.php:/var/www/html/w/LocalSettings.php
      - ./config/nginx:/etc/nginx/http.d
    labels:
      - traefik.http.routers.mediawiki.rule=Host(`staging.coasterpedia.net`)
      - traefik.http.routers.mediawiki.entrypoints=web,websecure
      - traefik.http.services.mediawiki.loadbalancer.server.port=80
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_SERVER: ${MYSQL_SERVER}
      MYSQL_USER: ${MYSQL_USER}
      SMTP_HOST: ${SMTP_HOST}
      SMTP_USER: ${SMTP_USER}
      SMTP_PASSWORD: ${SMTP_PASSWORD}
      AWS_REGION: ${AWS_REGION}
      AWS_BUCKET_NAME: ${AWS_BUCKET_NAME}
  redis:
    image: redis:alpine
    restart: unless-stopped
    init: true
    user: "${UID}:${GID}"
    security_opt:
      - no-new-privileges:true
    networks:
      - web
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - redis:/data
networks:
  web:
volumes:
  website:
  redis: