services:
  mediawiki:
    image: ghcr.io/coasterpedia/coasterpedia-web:${IMAGE}
    restart: always
    ports:
      - 80:80
    networks:
      - web
    volumes:
      - ./config/mediawiki/LocalSettings.php:/var/www/html/LocalSettings.php
      - ./config/nginx:/etc/nginx/http.d
  redis:
    image: redis:alpine
    restart: unless-stopped
    init: true
    user: "${UID}:${GID}"
    security_opt:
      - no-new-privileges:true
    networks:
      - web
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - redis:/data
networks:
  web:
volumes:
  website:
  redis: