services:
  mediawiki:
    image: ghcr.io/coasterpedia/coasterpedia-web@${IMAGE}
    restart: always
    ports:
      - 80:80
    networks:
      - web
    volumes:
      - ./config/mediawiki/LocalSettings.php:/var/www/html/w/LocalSettings.php
      - ./config/nginx:/etc/nginx/http.d
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_SERVER: ${MYSQL_SERVER}
      MYSQL_USER: ${MYSQL_USER}
      SMTP_HOST: ${SMTP_HOST}
      SMTP_USER: ${SMTP_USER}
      SMTP_PASSWORD: ${SMTP_PASSWORD}
  redis:
    image: redis:alpine
    restart: unless-stopped
    init: true
    user: "${UID}:${GID}"
    security_opt:
      - no-new-privileges:true
    networks:
      - web
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - redis:/data
networks:
  web:
volumes:
  website:
  redis: