name: Docker
on:
  schedule:
    - cron: '23 4 * * *'
  push:
    branches: [ "main" ]
    # Publish semver tags as releases.
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ "main" ]

env:
  REGISTRY: ghcr.io

jobs:
  mediawiki_build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    env:
      IMAGE_NAME: Coasterpedia/coasterpedia-web/mediawiki

    outputs:
      digest: ${{steps.build-and-push.outputs.digest}}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      # Set up BuildKit Docker container builder to be able to build
      # multi-platform images and export cache
      # https://github.com/docker/setup-buildx-action
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Login against a Docker registry except on PR
      # https://github.com/docker/login-action
      - name: Log into registry ${{ env.REGISTRY }}
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Extract metadata (tags, labels) for Docker
      # https://github.com/docker/metadata-action
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      # Build and push Docker image with Buildx (don't push on PR)
      # https://github.com/docker/build-push-action
      - name: Build and push Docker image
        id: build-and-push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile-mediawiki
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha,scope=${{ github.ref_name }}-mediawiki
          cache-to: type=gha,mode=max,scope=${{ github.ref_name }}-mediawiki
          platforms: linux/arm64

  matomo_build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    env:
      IMAGE_NAME: Coasterpedia/coasterpedia-web/matomo

    outputs:
      digest: ${{steps.build-and-push.outputs.digest}}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      # Set up BuildKit Docker container builder to be able to build
      # multi-platform images and export cache
      # https://github.com/docker/setup-buildx-action
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Login against a Docker registry except on PR
      # https://github.com/docker/login-action
      - name: Log into registry ${{ env.REGISTRY }}
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Extract metadata (tags, labels) for Docker
      # https://github.com/docker/metadata-action
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      # Build and push Docker image with Buildx (don't push on PR)
      # https://github.com/docker/build-push-action
      - name: Build and push Docker image
        id: build-and-push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile-matomo
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha,scope=${{ github.ref_name }}-matomo
          cache-to: type=gha,mode=max,scope=${{ github.ref_name }}-matomo
          platforms: linux/arm64

  jobrunner_build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    env:
      IMAGE_NAME: Coasterpedia/coasterpedia-web/jobrunner

    outputs:
      digest: ${{steps.build-and-push.outputs.digest}}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      # Set up BuildKit Docker container builder to be able to build
      # multi-platform images and export cache
      # https://github.com/docker/setup-buildx-action
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Login against a Docker registry except on PR
      # https://github.com/docker/login-action
      - name: Log into registry ${{ env.REGISTRY }}
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Extract metadata (tags, labels) for Docker
      # https://github.com/docker/metadata-action
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      # Build and push Docker image with Buildx (don't push on PR)
      # https://github.com/docker/build-push-action
      - name: Build and push Docker image
        id: build-and-push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile-jobrunner
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha,scope=${{ github.ref_name }}-jobrunner
          cache-to: type=gha,mode=max,scope=${{ github.ref_name }}-jobrunner
          platforms: linux/arm64

  deploy:
    runs-on: ubuntu-latest
    needs: [mediawiki_build, matomo_build, jobrunner_build]
    permissions:
      contents: read

    steps:
      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.DOCKER_SSH_PRIVATE_KEY }}
          known_hosts: ${{ secrets.DOCKER_SSH_KNOWN_HOSTS }}
      
      - name: Deploy to server
        run: >
          ssh ${{ secrets.DOCKER_HOST }} '
            export MEDIAWIKI_IMAGE="${{needs.mediawiki_build.outputs.digest}}" &&
            export MATOMO_IMAGE="${{needs.matomo_build.outputs.digest}}" &&
            export JOBRUNNER_IMAGE="${{needs.jobrunner_build.outputs.digest}}" &&
            export MYSQL_DATABASE="${{secrets.MYSQL_DATABASE}}" &&
            export MYSQL_PASSWORD="${{secrets.MYSQL_PASSWORD}}" &&
            export MYSQL_SERVER="${{secrets.MYSQL_SERVER}}" &&
            export MYSQL_USER="${{secrets.MYSQL_USER}}" &&
            export SMTP_HOST="${{secrets.SMTP_HOST}}" &&
            export SMTP_USER="${{secrets.SMTP_USER}}" &&
            export SMTP_PASSWORD="${{secrets.SMTP_PASSWORD}}" &&
            export AWS_REGION="${{secrets.AWS_REGION}}" &&
            export AWS_BUCKET_NAME="${{secrets.AWS_BUCKET_NAME}}" &&
            export MATOMO_DATABASE_DBNAME="${{secrets.MATOMO_DATABASE_DBNAME}}" &&
            export MATOMO_DATABASE_PASSWORD="${{secrets.MATOMO_DATABASE_PASSWORD}}" &&
            export MATOMO_DATABASE_HOST="${{secrets.MATOMO_DATABASE_HOST}}" &&
            export MATOMO_DATABASE_USERNAME="${{secrets.MATOMO_DATABASE_USERNAME}}" &&
            export SECRET_KEY="${{secrets.SECRET_KEY}}" &&
            export ES_IP="${{secrets.ES_IP}}" &&
            touch  oauth_public.key &&
            echo ${{secrets.OAUTH_PUBLIC}} >> oauth_public.key &&
            touch  oauth_private.key &&
            echo ${{secrets.OAUTH_PRIVATE}} >> oauth_private.key &&
            if cd coasterpedia; then git pull; else git clone --depth 1 -b main https://github.com/${{ github.repository }} coasterpedia; fi &&
            docker compose pull &&
            docker compose up -d -V &&
            docker system prune -f &&
            docker volume prune -f
          '